services:
  
  # nginx proxies all http requests to the right service 
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./configs/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./configs/.htpasswd:/etc/nginx/.htpasswd
    ports:
      - "8080:8080"

  # frontend service
  frontend:
    image: vm014.qu.tu-berlin.de:6000/csd-frontend-amd64
    platform: linux/amd64/v3
    volumes:
      - ./configs/frontend-assets/:/app/user-assets/

  # animalbot service - combines API and web interface
  animalbot:
    build:
      context: .
      dockerfile: chatbot/Dockerfile
    ports:
      - "8001:8000"  # FastAPI
      - "8502:8501"  # Streamlit
    volumes:
      - ./data:/app/data
      - ./chatbot:/app
    environment:
      - CHAT_AI_ACCESS_KEY=${CHAT_AI_ACCESS_KEY}
    stdin_open: true
    tty: true
    restart: unless-stopped
